-- MySQL Script generated by MySQL Workbench
-- Mon Nov 20 18:25:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `idArea` INT NOT NULL,
  `NombreArea` VARCHAR(45) NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medico` (
  `idMedico` INT NOT NULL AUTO_INCREMENT,
  `Area` VARCHAR(45) NULL,
  `NombreDoctor` VARCHAR(45) NULL,
  `ApellidoDoctor` VARCHAR(45) NULL,
  `Direccion` VARCHAR(70) NULL,
  `Email` VARCHAR(30) NULL,
  `Telefono` VARCHAR(13) NULL,
  `Area_idArea` INT NOT NULL,
  PRIMARY KEY (`idMedico`),
  INDEX `fk_Medico_Area1_idx` (`Area_idArea` ASC),
  CONSTRAINT `fk_Medico_Area1`
    FOREIGN KEY (`Area_idArea`)
    REFERENCES `mydb`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `Identidad` VARCHAR(13) NULL,
  `Nom_Paciente` VARCHAR(45) NULL,
  `Apellido_Pnte` VARCHAR(45) NULL,
  `Genero_Pnte` VARCHAR(2) NULL,
  `Fecha_Nacimiento` DATE NULL,
  `Direccion` VARCHAR(60) NULL,
  `Email` VARCHAR(30) NULL,
  `Telefono` VARCHAR(13) NULL,
  `Diagnostico` VARCHAR(300) NULL,
  `Medicamentos` VARCHAR(100) NULL,
  `Alergias` VARCHAR(100) NULL,
  `Medico_idMedico` INT NOT NULL,
  PRIMARY KEY (`idPaciente`),
  INDEX `fk_Paciente_Medico_idx` (`Medico_idMedico` ASC),
  CONSTRAINT `fk_Paciente_Medico`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `mydb`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cita` (
  `idCita` INT NOT NULL,
  `Asunto` VARCHAR(45) NULL,
  `Paciente` VARCHAR(45) NULL,
  `Medico` VARCHAR(45) NULL,
  `Fecha` DATE NULL,
  `Hora` TIME NULL,
  `Nota` VARCHAR(300) NULL,
  `Diagnostico` VARCHAR(200) NULL,
  `Sintomas` VARCHAR(300) NULL,
  `Medicamentos` VARCHAR(200) NULL,
  `EstadoDeLaCita` VARCHAR(12) NULL,
  `EstadoDelPago` VARCHAR(12) NULL,
  `Costo` FLOAT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`idCita`),
  INDEX `fk_Cita_Paciente1_idx` (`Paciente_idPaciente` ASC),
  CONSTRAINT `fk_Cita_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
